### ISSUE TITLE
Auto create PR from new chapter submission form

### ISSUE THREAD

**Issue by colinmahns** [dsa-ntc/dsa-planet#18]
Would be nice to grab the inserted text from tickets and have it automatically create new chapters when they're requested. One-offs are less than five minutes of labor to handle but we should try to minimize a margin of error for copy/paste work.

- [x] Obtain info via issue template
- [x] Parse info into github action (maybe with https://github.com/issue-ops/parser)
- [x] Check URLs are valid
- [x] Download and save image (convert to .webp unless .svg)
- [x] Parse planet.ini
- [x] Add new entry to previous entries
- [x] Sort all entries
- [x] Write all entries to planet.ini
- [x] Auto-create pull request linked to issue

**Comment by bmos** [comment]
- [ ] Obtain info via issue template
- [ ] Parse info into github action (maybe with https://github.com/issue-ops/parser)
- [ ] Check URLs are valid
- [ ] Download and save image (convert to webp)
- [ ] Parse planet.ini
- [ ] Add new entry to previous entries
- [ ] Sort all entries
- [ ] Write all entries to planet.ini
- [ ] Auto-create pull request

**Comment by bmos** [comment]
https://github.com/dsa-ntc/dsa-planet/pull/57

**Comment by bmos** [comment]
https://github.com/dsa-ntc/dsa-planet/commit/3a2b5f566ea7447590fff97ca82527da51c042e4
Implemented remaining task (saving avatars locally as webp)
