### ISSUE TITLE
gwene.org (RSS to Usenet Gateway) unable to parse Feed url

### ISSUE THREAD

**Issue by cmahns** [dsa-ntc/dsa-planet#24]
Background
Related to #8 -- Looks like gwene.org's RSS feed reader is experiencing issues as a result of a malformed rss feed. 

Steps to Reproduce:
Tested with north.dsanj.org, central.dsanj.org, tech.dsanj.org, both Democratic Left feeds (democraticleft.dsausa.org, the print edition and dsausa.org/democratic-left, the blog), and both the Atom and RSS 2.0 feed.dsausa.org urls. Only had success adding north.dsanj.org and central.dsanj.org so this may not be an issue we can resolve since we're just repackaging upstream feeds. 

Expected behavior:
gwene should be able to parse either RSS 2.0 or Atom urls

Screenshots: 
![image](https://github.com/dsa-ntc/dsa-planet/assets/1781677/5ccaa010-21ad-409c-8d13-9bec95ecfe59)
![image](https://github.com/dsa-ntc/dsa-planet/assets/1781677/8b81f651-f85a-449f-8820-05354be57ca8)

**Comment by victoria-riley-barnett** [comment]
https://github.com/dsa-ntc/dsa-planet/pull/25#issue-1870173178

**Comment by bmos** [comment]
I just reached out to Émilia to see if there's anything that can be done to fix that regarding Cloudflare.

**Comment by bmos** [comment]
This issue can be closed.
Émilia added an exception and now it works.
