### ISSUE TITLE
Convert hackergotchi images to webp

### ISSUE THREAD

**Issue by cmahns** [dsa-ntc/dsa-planet#28]
Small performance improvement: convert all jpg, png, and svg to webp to shave off a few seconds here and there on load times. It's not a lot but on mobile on a bad connection. it really does make a difference

**Comment by bilalmirza74** [comment]
hi do you also wants do favicons to webp?

**Comment by bilalmirza74** [comment]
done merge my pr

**Comment by bilalmirza74** [comment]
converter give me pr
