### ISSUE TITLE
Remove last remaining OpenSUSE elements

### ISSUE THREAD

**Issue by cmahns** [dsa-ntc/dsa-planet#29]
Noticed a few other OpenSUSE elements in the code, some links to some OpenSUSE infrastructure like their Plausible instance, among a few small things we're not using anymore, can all likely get removed with little issue. Likely some small performance improvements.

**Comment by lediur** [comment]
Yeah I noticed that there are several hotlinks to `opensuse.org` domains `beans.opensuse.org` and `static.opensuse.org` :) 

likely:

https://github.com/dsa-ntc/dsa-planet/blob/2b1998dbe57976456759abbc18e903ebe9dc2173/_includes/head.html#L15
